language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t srinivas/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run -e CI=true srinivas/react-test npm test

after_success:
        - docker build -t ollekkam1/myrepo:multi-client ./client
        - docker build -t ollekkam1/myrepo:multi-worker ./worker
        - docker build -t ollekkam1/myrepo:multi-nginx ./nginx
        - docker build -t ollekkam1/myrepo:multi-server ./server
# login to docker cli

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take those images and push all of them to docker hub

        - docker push ollekkam1/myrepo:multi-client
        - docker push ollekkam1/myrepo:multi-worker
        - docker push ollekkam1/myrepo:multi-nginx
        - docker push ollekkam1/myrepo:multi-server

